language: php

sudo: false

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '8.0'
  - '8.2'
  - nightly

before_script:
  - if [ "$TRAVIS_PHP_VERSION" = "8.0" ]; then travis_retry composer require satooshi/php-coveralls; fi
  - travis_retry composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
  - ant travis

after_success:
  - if [ "$TRAVIS_PHP_VERSION" = "8.0" ]; then travis_retry php vendor/bin/coveralls -v; fi
