name: test
run-name: test
on:
  workflow_dispatch:
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions:
          - 8.2
          - 8.1
          - 8.0

    name: PHP ${{ matrix.php-versions }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          coverage: none

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit
      - name: Run static analysis
        run: vendor/bin/phpstan
